- packages/ui/src/global.css
> [⚙️ chore] global.css 수정

- apps/storybook/stories/Tooltip.stories.tsx
- packages/ui/src/components/Tooltip/Tooltip.tsx
> [✨ feat] 공통 컴포넌트 구현 (Tooltip)

- apps/web/app/layout.tsx
- apps/web/styles/global.css
global.css 에 max-width제거 >> 모바일에서 100% 보여야 함
추후 PC에서만 max-width적용하는걸로 수정예정
> [🐞 hotfix] Web CSS 수정

- apps/storybook/stories/Button.stories.tsx
- packages/ui/src/components/Button/Button.tsx
버튼안에 아이콘 포함시 ```<Button><Plus size={20} />버튼</Button>``` 과 같이 size 변경 가능하게 수정했습니다. 
원형 버튼은 ```<Button shape="rounded" className="size-10"><Plus /></Button>```과 같이 버튼 클래스에 size-* 넣어주시면 됩니다.
> [🐞 hotfix] 버튼 컴포넌트 수정

- apps/storybook/stories/Input.stories.tsx
- packages/ui/src/components/Dialog/Dialog.tsx
- packages/ui/src/components/Input/Input.tsx
[input 컴포넌트]
- export InputContent ->Input  변경 
- xIcon 부분 삭제 
- input type 속성 date , time 추가 
- input border 스타일 수정 
- input type-> date, time 아이콘 위치, 크기 설정
[input storybook]
- 컴포넌트 이름 :  InputContent ->Input 변경 
-스토리북 Title :  textinput -> Input 변경 
[Dialog 컴포넌트]
- dialog 팝업 시 dialog border 삭제
- dialog 팝업 시 ring 삭제
- dialog xIcon, 내용 겹치는 문제 수정
> [🐞 hotfix] dialog xicon 수정 및 input 수정

- pnpm-lock.yaml
> [🐞 hotfix] pnpm-lock 최신화

- apps/web/app/(header)/auction/[shortId]/BottomBar.tsx
- apps/web/features/mypage/edit/ui/ProfilePreview.tsx
- apps/web/shared/lib/ImageUploadPreview.tsx
- packages/ui/src/components/abcd/Abcd.tsx
> [🐞 hotfix] dialog 대소문자 구분

- apps/web/app/(header)/auction/[shortId]/BottomBar.tsx
- apps/web/features/mypage/edit/ui/ProfilePreview.tsx
- apps/web/shared/lib/ImageUploadPreview.tsx
- packages/ui/src/components/Dialog/Dialog.tsx
dialog 컴포넌트 Abcd->Dialog로 파일명 변경 
> [🐞 hotfix] dialog 대소문자 변경2 #98

- apps/web/app/api/product/route.ts
- apps/web/features/Product/ui/ProductItem.tsx
- apps/web/features/Product/ui/ProductList.tsx
closes #106 
ProductActionBtn 컴포넌트 경로 수정
> [🐞 hotfix] ProductActionBtn 컴포넌트 경로 수정

- apps/web/app/splash/page.tsx
로그인 유무에 따라, 유저의 위치 설정에 따라 "시작하기" 버튼 클릭시 페이지 이동 수정
> [🐞 hotfix] 토큰별, 위치 설정별 splash 페이지 이동

- apps/web/features/location/ui/LocationConfirm.tsx
- apps/web/widgets/header/ui/HeaderItem.tsx
> [✨ feat] 기능명세서기반 alert메세지로 수정 

- apps/web/app/api/product/route.ts
상품리스트 가격 min_price -> bid_price 로변경
> [🐞 hotfix] 상품리스트 가격 min_price -> bid_price 로변경

- apps/web/app/(header)/product/edit/[shortId]/page.tsx
- apps/web/app/api/product/edit/[shortId]/route.ts
> [🐞 hotfix] 상품 수정 시 이미지가 삭제되는 오류 수정

- apps/web/features/mypage/ui/MypageProfileCard.tsx
- apps/web/features/product/ui/ProductBadge.tsx
- apps/web/features/product/ui/ProductItem.tsx
closes #137
경매 상태 뱃지 수정, 입찰 횟수 미노출
> [🐞 hotfix] 경매 상태 뱃지 수정, 입찰 횟수 미노출

- apps/web/app/(base)/page.tsx
- apps/web/app/(header)/auction/[shortId]/BottomBar.tsx
- apps/web/app/(header)/product/edit/[shortId]/page.tsx
- apps/web/app/(header)/product/page.tsx
- apps/web/app/(header)/product/registration/page.tsx
- apps/web/app/(plane)/find-id/page.tsx
- apps/web/app/(plane)/reset-pw/page.tsx
- apps/web/app/auth/callback/page.tsx
- apps/web/app/layout.tsx
- apps/web/features/location/ui/LocationConfirm.tsx
- apps/web/features/mypage/edit/ui/ProfileInputList.tsx
- apps/web/features/product/ui/ProductActionBtn.tsx
- apps/web/features/search/ui/ResultSection.tsx
- apps/web/features/signup/SignUpForm.tsx
- packages/ui/src/components/Toast/Sonner.tsx
alert -> toast 로 변경 
console.log 삭제
> [✨ feat] alert -> toast 로 변경 

- apps/web/app/api/auction/[shortId]/route.ts
- apps/web/entities/auction/model/types.ts
- apps/web/entities/bidHistory/model/types.ts
- apps/web/features/auction/bids/ui/BidDialog.tsx
- apps/web/features/auction/detail/api/useBidHistoryRealtime.ts
- apps/web/features/auction/detail/types/index.ts
- apps/web/features/auction/detail/ui/AuctionDetailPage.tsx
- apps/web/features/auction/detail/ui/BiddingStatusBoard.tsx
- apps/web/shared/lib/supabaseClient.ts
- pnpm-lock.yaml
- 입찰현황판 구현
- supabase realtime 적용하여 페이지를 새로고침하지 않아도 실시간으로 데이터 반영
> [✨ feat] 입찰현황판 구현

- apps/web/features/auction/listings/model/getListingList.ts
> [🔧 fix] 출품 내역 금액 수정

- apps/web/app/(plane)/login/page.tsx
- apps/web/features/find-id/model/useFindId.ts
- apps/web/features/login/model/useLogin.ts
- apps/web/features/login/ui/LogInForm.tsx
- apps/web/shared/lib/validation/email.ts
- apps/web/app/(plane)/login/page.tsx
- apps/web/features/find-id/model/useFindId.ts
- apps/web/features/login/model/useLogin.ts
- apps/web/features/login/ui/LogInForm.tsx
- apps/web/shared/lib/validation/email.ts
> [♻️ refactor] 유효성 검사 로직 수정

- apps/web/features/find-id/model/useFindId.ts
- apps/web/features/find-id/model/useFindId.ts
> [♻️ refactor] 미등록자 비밀번호 찾기 실행 시 이메일 전송 이슈

- pnpm-lock.yaml
pnpm-lock 파일 ssr 버전 충돌 수정.
- pnpm-lock.yaml
> [🔧 fix] pnpm-lock 파일 수정

- apps/web/app/api/auth/login/route.ts
- apps/web/app/api/auth/me/route.ts
- apps/web/features/login/model/useLogin.ts
- apps/web/shared/lib/middleware/redirect.ts
- apps/web/shared/model/authStore.ts
- apps/web/shared/model/useAuth.ts
- apps/web/app/api/auth/me/route.ts
- apps/web/shared/lib/middleware/redirect.ts
- apps/web/shared/model/authStore.ts
- apps/web/shared/model/useAuth.ts
> [♻️ refactor] 미들웨어 인증 구현

- .github/workflows/release.yml
- apps/web/CHANGELOG.md
- apps/web/scripts/generate-release-notes.cjs
CHANGELOG.md 파일 생성
첫 배포용 v1.0.0 버전 히스토리 수동 작성
scripts/generate-release-notes.js 생성
GitHub Actions 워크플로우 추가
> [📜 docs] 릴리즈 노트 자동화 구축

- apps/web/shared/lib/auth.ts
> [🐞 hotfix] 회원가입 이메일 인증 리디렉션

- apps/web/app/(base)/layout.tsx
- apps/web/app/(base)/page.tsx
- apps/web/app/(header)/auction/[shortId]/page.tsx
- apps/web/app/(header)/layout.tsx
- apps/web/app/(plane)/find-id/page.tsx
- apps/web/app/(plane)/login/page.tsx
- apps/web/app/(plane)/signup/page.tsx
- apps/web/app/(plane)/splash/welcome/page.tsx
- apps/web/features/auction/detail/ui/AuctionDetailPage.tsx
- apps/web/features/auction/detail/ui/BottomBar.tsx
- apps/web/features/category/ui/InlineCategory.tsx
- apps/web/features/find-id/lib/findAccountConfig.tsx
- apps/web/features/login/ui/LogInForm.tsx
- apps/web/features/product/ui/LocationPin.tsx
- apps/web/features/product/ui/ProductRegistrationForm.tsx
- apps/web/features/signup/SignUpForm.tsx
- apps/web/features/signup/ui/ConfirmPassword.tsx
- apps/web/features/signup/ui/EmailField.tsx
- apps/web/features/signup/ui/NicknameField.tsx
- apps/web/features/signup/ui/PasswordField.tsx
- apps/web/shared/lib/ImageUploadPreview.tsx
- apps/web/styles/global.css
- packages/ui/src/components/Input/Input.tsx
- packages/ui/src/global.css
closes #189 
서비스 전체적으로 여백 및 폰트 수정
> [✨ design] css 수정

- apps/web/app/(header)/product/page.tsx
- apps/web/app/(plane)/find-id/page.tsx
- apps/web/app/(plane)/login/page.tsx
- apps/web/app/(plane)/signup/page.tsx
- apps/web/features/find-id/model/useFindId.ts
- apps/web/features/login/ui/LogInForm.tsx
- apps/web/features/signup/SignUpForm.tsx
- apps/web/shared/lib/auth.ts
- apps/web/shared/lib/middleware/redirect.ts
- apps/web/app/(header)/product/page.tsx
- apps/web/app/(plane)/find-id/page.tsx
- apps/web/app/(plane)/login/page.tsx
- apps/web/app/(plane)/signup/page.tsx
- apps/web/features/find-id/model/useFindId.ts
- apps/web/features/login/ui/LogInForm.tsx
- apps/web/features/signup/SignUpForm.tsx
- apps/web/shared/lib/middleware/redirect.ts
> [🐞 hotfix] 비번찾기 이메일인증 리디렉션 재연결

- .github/workflows/release.yml
scripts/generate-release-notes.js 확장자를 cjs로 변경
> [🔧 fix] release파일 수정

- apps/web/.github/workflows/cron-auction.yml
- apps/web/.github/workflows/cron-resolve-auction.yml
- apps/web/app/api/cron/create-auction/route.ts
- apps/web/app/api/cron/resolve-auction/route.ts
- 경매 상품 스케줄러 로직에 배포 URL 설정
- 경매 상품 스케줄러 로직에서 for문을 병렬 작업으로 변경
> [✨ feat] 경매 상품 관련 스케줄러 로직에 배포 URL 설정

- apps/web/app/(base)/layout.tsx
- apps/web/app/(header)/auction/bids/page.tsx
- apps/web/app/(header)/auction/listings/page.tsx
- apps/web/app/(header)/layout.tsx
- apps/web/app/(header)/product/page.tsx
- apps/web/features/auction/bids/index.tsx
- apps/web/features/auction/listings/index.tsx
- apps/web/features/auction/shared/types/index.ts
- apps/web/features/auction/shared/ui/UrlSyncTabs.tsx
- apps/web/features/mypage/types/index.ts
- apps/web/features/mypage/ui/MyPageAuction.tsx
- apps/web/features/mypage/ui/MyPageAuctionCard.tsx
- apps/web/features/product/ui/ProductRegistrationForm.tsx
- apps/web/widgets/nav/Nav.tsx
- packages/ui/src/components/Dialog/Dialog.tsx
closes #274 
이슈 테스트 전 수정사항 반영
* apps/web/app/(header)/layout.tsx
* apps/web/app/(header)/layout.tsx
* apps/web/widgets/nav/Nav.tsx
* packages/ui/src/components/Dialog/Dialog.tsx
> [🔧 fix] 경매 대기 안내 추가, 내 경매 상태 링크 연결

- scripts/generate-release-notes.cjs
릴리즈노트 hotfix가 others로 분류되는 버그 수정
> [🐞 hotfix] 릴리즈 자동화 병렬실행방지

- apps/web/shared/lib/ImageUploadPreview.tsx
- package.json
develop <-> deploy 동기화
출품하기 이미지 삭제 버튼 크기 에러 수정
> develop <-> deploy 동기화

- apps/web/features/auction/detail/api/useBidHistoryRealtime.ts
- apps/web/features/auction/detail/types/index.ts
- apps/web/features/auction/detail/ui/AuctionDetailPage.tsx
- apps/web/features/auction/detail/ui/BiddingStatusBoard.tsx
- 입찰현황판 realtime 쿼리에 해당 경매 상품의 상세 조회 캐시 삭제 로직 추가
- realtime 로직에 auction_id 값을 전달하도록 수정
> [🐞 hotfix] 입찰현황판 관련 이슈

- apps/web/app/api/product/route.ts
- apps/web/entities/auction/model/types.ts
최신순 필터링 버그
최신순 필터링이 경매 종료일로 필터링되고 있어서 경매 등록일로 수정
> [🐞 hotfix] 최신순 필터링 버그

- apps/web/app/layout.tsx
- apps/web/widgets/nav/Nav.tsx
- packages/ui/src/global.css
> [⚙️ chore] RootLayout 수정

- apps/web/features/auction/bids/model/useBidSubmit.ts
- apps/web/features/auction/detail/api/useBidHistoryRealtime.ts
- package.json
입찰 후 상세페이지 조회 시 직전 입찰이 반영되지 않은 화면 이슈
> deploy <-> develop 동기화

- apps/web/app/api/auction/[shortId]/route.ts
- apps/web/entities/product/model/types.ts
- apps/web/entities/productImage/model/types.ts
- apps/web/features/auction/detail/lib/generateBlurImg.ts
- apps/web/features/auction/detail/ui/ProductImageSlider.tsx
- apps/web/package.json
- pnpm-lock.yaml
> [♻️ refactor] 상품 상세페이지 성능개선 - 이미지 blur 적용

- apps/web/features/product/model/useCreateProduct.ts
상품 출품 시 제목, 설명, 위치 설명에 대하여 공백만 입력된 채로 넘어가지 않도록 제한 설정
> [🐞 hotfix] 출품 시 공백이 입력된 상태로 넘어가지 않도록 처리

- apps/web/app/(plane)/search/page.tsx
- apps/web/features/auction/list/ui/AuctionFilter.tsx
- apps/web/features/auction/list/ui/AuctionList.tsx
- apps/web/features/auction/list/ui/AuctionListClientPage.tsx
- apps/web/features/auction/list/ui/AuctionTooltip.tsx
- apps/web/features/home/ui/HomeClientPage.tsx
- apps/web/features/search/ui/ResultSection.tsx
- apps/web/features/search/ui/SearchClientPage.tsx
GoogleMapView, AuctionSortDropdown, AuctionList 세개 컴포넌트를 초기 번들에서 제외시킴
AuctionList가 내부에서 데이터 가져오도록 책임 분리.
검색페이지 서버컴포넌트로 변경
dynamic import 코드추가
> googleMapView컴포넌트 dynamic import 적용

- apps/web/app/(header)/mypage/edit/page.tsx
- apps/web/app/(header)/mypage/point/page.tsx
- apps/web/app/(header)/mypage/proposal/received/[proposalId]/page.tsx
- apps/web/app/(header)/mypage/proposal/received/page.tsx
- apps/web/app/(header)/mypage/proposal/sent/page.tsx
- apps/web/app/(plane)/(location)/set-location/page.tsx
- apps/web/app/(plane)/(location)/update-location/page.tsx
- apps/web/app/(plane)/alarm/page.tsx
- apps/web/app/(plane)/find-id/page.tsx
- apps/web/app/(plane)/login/page.tsx
- apps/web/app/(plane)/reset-pw/page.tsx
- apps/web/app/(plane)/signup/page.tsx
- apps/web/features/mypage/edit/index.tsx
- apps/web/features/proposal/make/ui/MakeProposal.tsx
develop브랜치에 추가된 페이지들 QueryProvider추가
> [🐞 hotfix] develop브랜치에 추가된 페이지들 QueryProvider추가
